services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"  # <-- This is the missing line
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=url_db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  # <-- Adminer runs on 8080, not 5432
